version: "3.2"

services:
  message_broker:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"  
  db:
    image: postgres:15.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: strong
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "82:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@domain.local"
      PGADMIN_DEFAULT_PASSWORD: "postmaster"
    depends_on:
      - db
